import { Geist, Geist_Mono } from "next/font/google";
import { Poppins, Montserrat } from "next/font/google";
import "./globals.css";
import "../css/style.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap", // Menambahkan display: swap
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap", // Menambahkan display: swap
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: "400", // Specify a valid weight for Poppins
  display: "swap", // Menambahkan display: swap
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: "400", // Specify a valid weight for Montserrat
  display: "swap", // Menambahkan display: swap
});

export const metadata = {
  title: "Portfolio Website",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // Optional favicon
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Font Awesome */}
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${montserrat.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
